adding portfolio desktop version
Nejjari001/Portfolio-setup-and-mobile-firs pull request #7
Opened 2022-09-01 17:17 UTC by Nejjari001

setup the portfolio version desktop

2022-09-01 18:52 UTC, CollinsTatang requested changes
Hi @Nejjari001 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- 
## Required changes 
It's ok to have bugs in your code. Please, see this code review as a chance for you to learn practical coding skills and learn new tips that can improve your code quality and help you get a better job.

- [ ] Please update your readme file and the [descriptive summary](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) of your pull request.

_Check the comments under the review._
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-01 18:52 UTC, CollinsTatang commented on styles.css
> +  width: auto;
- [ ] Please kindly work on the design to match the [figmal design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=34%3A848)
**Your Design**
![you](https://user-images.githubusercontent.com/55596970/187988026-d3d4989b-7645-4232-8d0f-da247f8adefd.png)
**Figmal Design**
![skill_Yours](https://user-images.githubusercontent.com/55596970/187988116-71984cd4-37c0-4125-93b9-63c56facbee3.png)

2022-09-01 18:52 UTC, CollinsTatang commented on styles.css
> +  width: auto;
- [ ] Please kindly work on the background design to match that of [figmal](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=34%3A848)
**Your Design**
![yourStyle](https://user-images.githubusercontent.com/55596970/187989022-31363685-b2f7-4f57-abd4-72163db89adf.png)
**Figmal Design**
![figmal_contact](https://user-images.githubusercontent.com/55596970/187989140-752daf24-ceb5-4513-9cf7-fa65f609b85b.png)

2022-09-02 08:17 UTC, emmiiorji approved these changes
Hi @Nejjari001, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![congratulations](https://user-images.githubusercontent.com/20554583/188095826-7dfb8896-3696-4039-8730-c5200b355c39.gif)


## Good Highlights ✅

- Adherence to GitHub flow
- Implement suggested changes
- Good commit messages


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-02 08:39 UTC, merged